### ISSUE TITLE
service is running.

### ISSUE THREAD

**Issue by Kapp1** [roshub/http-to-https#3]
k@kall:~$ snap install http-to-https
http-to-https 1.0.0 from RosHub Inc (roshub) installed
k@kall:~$ snap set http-to-https port=80
error: access denied (try with sudo)
k@kall:~$ sudo set http-to-https port=80
[sudo] password for k: 
sudo: set: command not found

**Comment by mattlxdesign** [comment]
Hi Kapp1,
I don't know if you're still having trouble but try
`sudo snap set http-to-https port=80`
should do the trick
